# config reference: https://doc.rust-lang.org/cargo/reference/config.html

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals", "-C", "link-arg=--max-memory=4294967296"]

[unstable]
build-std = ["panic_abort", "std"]

[build]
target = "aarch64-apple-darwin"  # default build
